my_app/child/models.py
from my_app import db
from flask_wtf import FlaskForm
from wtforms import StringField, FormField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired
from my_app.parent.models import Parent, ParentForm
from datetime import date, datetime

# mongo document schema for Child
class Child(db.Document):
	first_name = db.StringField(maxlength=255, required=True)
	last_name = db.StringField(maxlength=255, required=True)
	birthday = db.DateTimeField(required=True)
	age_group = db.IntField()
	parent = db.EmbeddedDocumentListField(Parent)

	def calculate_age_group(self, birthday):
		today = date.today()
		months = ((today.year - birthday.year) * 12 ) + birthday.month
		age_group = None
		
		if months >= 36:
			age_group = 4
		elif months >= 12 and months < 36:
			age_group = 3
		elif months >= 6 and months < 12:
			age_group = 2
		elif months > 0 and months < 6:
			age_group = 1
		else:
			return "Could not calculate age group"

		return age_group

	def __repr__(self):
		return "<Children %r>" % self.id

# form schema to add a child
class ChildForm(FlaskForm):
	first_name = StringField("First name", validators=[InputRequired()])
	last_name = StringField("Last name", validators=[InputRequired()])
	birthday = DateField("Birthday", validators=[InputRequired()], format='%Y-%m-%d')
	parent = FormField(ParentForm)


def group_age_group(children):
	age_group = {
		"age_group_1_count": len([child for child in children if child.age_group == 1]),
		"age_group_2_count": len([child for child in children if child.age_group == 2]),
		"age_group_3_count": len([child for child in children if child.age_group == 3]),
		"age_group_4_count": len([child for child in children if child.age_group == 4])
	}	

	return age_group

my_app/parent/models.py
from my_app import db
from bson import ObjectId
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired


# mongo document schema for Child
class Parent(db.EmbeddedDocument):
	_id = db.ObjectIdField(default=ObjectId)
	first_name = db.StringField(maxlength=255, required=True)
	last_name = db.StringField(maxlength=255, required=True)

	def __repr__(self):
		return "<Parent %r>" % self._id

# form schema to add a child
class ParentForm(FlaskForm):
	first_name = StringField("First name", validators=[InputRequired()])
	last_name = StringField("Last name", validators=[InputRequired()])

my_app/__init__.py
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_login import LoginManager
import ssl


# app config
app = Flask(__name__)
app.config.from_object("configuration.DevelopmentConfig")


# mongo_db config
db = MongoEngine(app)


# authentication config
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "auth.login"


# register blueprints
from my_app.child.views import child_blueprint
app.register_blueprint(child_blueprint)

from my_app.auth.views import auth_blueprint
app.register_blueprint(auth_blueprint)

my_app/child/views.py
from flask import render_template, request, redirect, url_for, Blueprint
from flask_login import login_required
from my_app.child.models import Child, ChildForm, group_age_group
from my_app.parent.models import Parent, ParentForm

child_blueprint = Blueprint("child", __name__)

# context_processor to combine child's first_name and last_name
@child_blueprint.context_processor
def full_name_processor():
	def full_name(name):
		return "{0} {1}".format(name["first_name"], name["last_name"])

	return {"full_name": full_name}


@child_blueprint.route("/dashboard")
@login_required
def dashboard():
	children = Child.objects.all()
	age_group = group_age_group(children)

	return render_template("dashboard.html", children=children, age_group=age_group)


@child_blueprint.route("/add", methods=["GET", "POST"])
@login_required
def add():
	form = ChildForm(meta={'csrf': False})

	if request.method == "POST":
		parent = Parent (
			first_name = form.parent.first_name.data,
			last_name = form.parent.last_name.data
		)

		new_parent = Parent (
			first_name = "Coridon",
			last_name = "Grundy"
		)

		child = Child (
			first_name = form.first_name.data,
			last_name = form.last_name.data,
			birthday = form.birthday.data,
			parent = [parent, new_parent]
		)

		child.age_group = child.calculate_age_group(form.birthday.data)
		child.save()

		return redirect(url_for("child.dashboard"))
	
	return render_template("add-child.html", form=form)


@child_blueprint.route("/view/<id>")
@login_required
def view_child(id):
	child = Child.objects.get(id=id)

	return render_template("view-child.html", child=child)


@child_blueprint.route("/edit/<id>", methods=["GET", "POST"])
@login_required
def edit_child(id):
	child = Child.objects.get(id=id)

	form = ChildForm(meta={'csrf': False})

	if request.method == "POST":
		parent.update(
			first_name = form.parent.first_name.data,
			last_name = form.parent.last_name.data,
			phone = form.parent.phone.data,
			address = form.parent.address.data,
		)

		age_group = child.calculate_age_group(form.birthday.data)

		child.update (
			first_name = form.first_name.data,
			last_name = form.last_name.data,
			birthday = form.birthday.data,
			age_group = age_group,
			parent = parent
		)

		return redirect(url_for("child.view_child", id=id))

	return render_template("edit-child.html", child=child, form=form)


@child_blueprint.route("/delete/<id>")
@login_required
def delete_child(id):
	child = Child.objects.get_or_404(id=id)

	child.delete()

	return redirect(url_for("child.dashboard"))

my_app/parent/__init__.py
# No content
# We need this file just to make this folder a python module

my_app/parent/views.py
from flask import render_template, request, redirect, url_for, Blueprint
from flask_login import login_required
from my_app.parent.models import Parent, ParentForm
from my_app.child.models import Child, ChildForm


parent_blueprint = Blueprint("parent", __name__)

my_app/templates/add-child.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<h1>Add a child</h1>

		<form action="{{ url_for('child.add') }}" method="POST" role="form">

			<h4>Child information</h4>
			<div>{{ form.first_name.label }}</div>
			<div>{{ form.first_name() }}</div>

			<div>{{ form.last_name.label }}</div>
			<div>{{ form.last_name() }}</div>

			<div>{{ form.birthday.label }}</div>
			<div>{{ form.birthday() }}</div>

			<h4>Parent information</h4>
			<div>{{ form.parent.first_name.label }}</div>
			<div>{{ form.parent.first_name() }}</div>

			<div>{{ form.parent.last_name.label }}</div>
			<div>{{ form.parent.last_name() }}</div>

			<div class="row util-margin-top-30">
				<div class="col s12">
					<button class="btn" type="submit">Submit</button>
					<a class="btn-flat" href="{{ url_for('child.dashboard') }}">Cancel</a>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

my_app/templates/add-parent.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<h1>Add a parent</h1>

		<form action="{{ url_for('parent.add') }}" method="POST" role="form">

			<div>{{ form.first_name.label }}</div>
			<div>{{ form.first_name() }}</div>

			<div>{{ form.last_name.label }}</div>
			<div>{{ form.last_name() }}</div>

			<button class="btn" type="submit">Submit</button>
			<a class="btn-flat" href="{{ url_for('child.dashboard') }}">Cancel</a>
		</form>
	</div>
</div>
{% endblock %}

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Flask Framework Cookbook</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
	<div class="container">
		{% block container %}{% endblock %}
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

my_app/templates/dashboard.html
{% extends "base.html" %}

{% block container %}
<div>
	<div class="row">
		<div class="col s12">
			<h1>Dashboard</h1>
		</div>
	</div>

	<div class="row">
		<div class="col s6">
			<a class="btn" href="{{ url_for('child.add') }}"><i class="material-icons right">add</i> Add Child</a>
		</div>
		<div class="col s6">
			<a class="btn" href="{{ url_for('auth.logout')}}">Log out</a>
		</div>
	</div>

	<div class="age-group--wrapper row">
		<div class="age-group--container col s3">
			<div class="card teal">
				<div class="card-content white-text">
					<span class="card-title center">Age Group #1</span>
					<p class="age-group--count">{{ age_group.age_group_1_count }}</p>
				</div>
			</div>
		</div>

		<div class="age-group--container col s3">
			<div class="card teal">
				<div class="card-content white-text">
					<span class="card-title center">Age Group #2</span>
					<p class="age-group--count">{{ age_group.age_group_2_count }}</p>
				</div>
			</div>
		</div>

		<div class="age-group--container col s3">
			<div class="card teal">
				<div class="card-content white-text">
					<span class="card-title center">Age Group #3</span>
					<p class="age-group--count">{{ age_group.age_group_3_count }}</p>
				</div>
			</div>
		</div>

		<div class="age-group--container col s3">
			<div class="card teal">
				<div class="card-content white-text">
					<span class="card-title center">Age Group #4</span>
					<p class="age-group--count">{{ age_group.age_group_4_count }}</p>
				</div>
			</div>
		</div>
	</div>

	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Age Group</th>
				<th>Action</th>
			</tr>
		</thead>

		<tbody>
			{% for child in children %}
			<tr>
				<td>{{ full_name(child) }}</td>
				<td>{{ child["age_group"] }}</td>
				<td>
					<a class="blue-text" href="{{ url_for('child.view_child', id=child['id']) }}">View child</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

my_app/templates/edit-child.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<h1>Edit a child</h1>

		<form action="{{ url_for('child.edit_child', id=child['id']) }}" method="POST" role="form">

			<h4>Child information</h4>
			<div>{{ form.first_name.label }}</div>
			<div>{{ form.first_name(value=child.first_name) }}</div>

			<div>{{ form.last_name.label }}</div>
			<div>{{ form.last_name(value=child.last_name) }}</div>

			<div>{{ form.birthday.label }}</div>
			<div>{{ form.birthday(value=child.birthday.strftime('%Y-%m-%d')) }}</div>

			<h4 class="util-margin-top-60">Parent information</h4>
			{% for parent in child.parent %}
			<div class="util-margin-top-30">
				<div>{{ form.parent.first_name.label }}</div>
				<div>{{ form.parent.first_name(value=parent.first_name) }}</div>

				<div>{{ form.parent.last_name.label }}</div>
				<div>{{ form.parent.last_name(value=parent.last_name) }}</div>
			</div>
			{% endfor %}

			<div class="row util-margin-top-30">
				<div class="col s12">
					<button class="btn" type="submit">Submit</button>
					<a class="btn-flat" href="{{ url_for('child.view_child', id=child['id']) }}">Back to view</a>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

my_app/templates/edit-parent.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<form action="{{ url_for('parent.edit_parent', id=child['id']) }}" method="POST" role="form">


			<h4 class="util-margin-top-60">Edit <span class="teal-text">{{ full_name(child) }}</span> parent's information</h4>
			<h4 class="util-margin-top-60">{{ parent.id }}</h4>
			<div class="util-margin-top-30">
				<div>{{ form.first_name.label }}</div>
				<div>{{ form.first_name(value=parent.first_name) }}</div>

				<div>{{ form.last_name.label }}</div>
				<div>{{ form.last_name(value=parent.last_name) }}</div>

				<div>{{ form.phone.label }}</div>
				<div>{{ form.phone(value=parent.phone) }}</div>

				<a id="js-add-address-line" href="#">Add Address Line</a>

				<div id="subforms-container">
					{% for subform in form.address %}
					<div id="address-{{ loop.index0 }}-form" data-index="{{ loop.index0 }}">
						{{ subform.address_line.label }}
						{{ subform.address_line(value=parent.address) }}
						<a class="js-remove-address-line" href="#">Remove</a>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="row util-margin-top-30">
				<div class="col s12">
					<button class="btn" type="submit">Submit</button>
					<a class="btn-flat" href="{{ url_for('child.view_child', id=child['id']) }}">Back to child</a>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

my_app/templates/login.html
{% extends "base.html" %}

{% block container %}

<div class="page-login">
	<div class="row">
		<div class="col s6 offset-s3">
			{% if current_user.is_authenticated %}
			<h4>You're already logged in</h4>
			<a class="btn util-margin-top-30" href="{{ url_for('child.dashboard') }}"><i class="material-icons left">arrow_back</i>Go to dashboard</a>
			<a class="btn-flat util-margin-top-30" href="{{ url_for('auth.logout')}}">Log out</a>
			{% else %}
			<div class="card">
				<div class="card-content">
					<span class="card-title">Log in</span>
					<form method="POST" action="{{ url_for('auth.login') }}" role="form">

						<div>{{ form.username.label }}</div>
						<div>{{ form.username() }}</div>

						<div>{{ form.password.label }}</div>
						<div>{{ form.password() }}</div>

						<button type="submit" class="btn util-margin-top-30">Submit</button>
					</form>

				</div>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

my_app/templates/register.html
{% extends "base.html" %}

{% block container %}

<h1>Register</h1>

<form method="POST" action="{{ url_for('auth.register') }}" role="form">

	<div>{{ form.username.label }}</div>
	<div>{{ form.username() }}</div>

	<div>{{ form.password.label }}</div>
	<div>{{ form.password() }}</div>

	<div>{{ form.confirm.label }}</div>
	<div>{{ form.confirm() }}</div>

	{% if form.errors %}
	<p>There's an error with your:</p>
	<ul>
		{% for error in form.errors %}
		<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	<button type="submit" class="btn">Submit</button>
</form>

{% endblock %}

my_app/templates/view-child.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<h1>{{ full_name(child) }}</h1>

		<div class="card">
			<div class="card-content util-margin-bottom-60">
				<span class="card-title teal white-text util-padding-left-15 util-padding-vert-5">Child's Information</span>
				<table>
					<thead>
						<tr class="util-margin-top-30">
							<th>&nbsp;</th>
							<th>&nbsp;</th>
						</tr>
					</thead>

					<tbody>
						<tr>
							<td>Birthday</td>
							<td>{{ child.birthday.strftime('%Y-%m-%d') }}</td>
						</tr>
						<tr>
							<td>Age group</td>
							<td>{{ child.age_group }}</td>
						</tr>
					</tbody>
				</table>

				<span class="card-title util-margin-top-60 teal white-text util-padding-left-15 util-padding-vert-5">Gaurdian's Information</span>
				{% for parent in child.parent %}
				<table>
					<thead>
						<tr>
							<th class="util-margin-top-60">{{ full_name(parent) }}</th>
							<th>&nbsp;</th>
						</tr>
					</thead>

					<tbody>
						<tr>
							<td>Phone</td>
							<td>{{ parent.first_name }}</td>
						</tr>
						<tr>
							<td>Address</td>
							<td>{{ parent.first_name }}</td>
						</tr>
					</tbody>
				</table>
				{% endfor %}
			</div>

			<div class="card-action">
				<a class="blue-text btn-flat" href="{{ url_for('child.edit_child', id=child['id']) }}"><i class="material-icons left">edit</i>Edit child</a>
				<a class="red-text btn-flat" href="{{ url_for('child.delete_child', id=child['id']) }}"><i class="material-icons left">delete</i>Delete child</a>
			</div>
		</div>

		<a class="btn" href="{{ url_for('child.dashboard') }}"><i class="material-icons left">arrow_back</i>Back to dashboard</a>
	</div>
</div>
{% endblock %}

my_app/templates/view-parent.html
{% extends "base.html" %}

{% block container %}
<div class="row">
	<div class="col s12">
		<h1>View a parent</h1>

		<div class="card">
			<div class="card-content">
				<span class="card-title">{{ child.parent.first_name }} {{ child.parent.last_name }}</span>
				<p>Parent to: {{ child.first_name }} {{ child.last_name }}</p>
			</div>
		</div>

		<a class="btn" href="{{ url_for('child.view_child', id=child['id']) }}"><i class="material-icons left">arrow_back</i>Back to dashboard</a>
	</div>
</div>
{% endblock %}